name: Trigger Netlify Build
on:
  schedule:
    # Run at 16:00 UTC / 03:00 AEST daily
    - cron: "0 16 * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/653747092d529320794535d1
